<?php

function acf_banner()
{
    return array(
		array(
			'key' => 'field_60ff052d8e5b6',
			'label' => 'Top Banner',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_60ff053d8e5b7',
			'label' => 'Image',
			'name' => 'banner_image',
			'type' => 'image',
			'instructions' => 'Recommended size 550x450.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_60ff055e8e5b8',
			'label' => 'Title',
			'name' => 'banner_title',
			'type' => 'text',
			'instructions' => 'Max characters: 20',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Banner title',
			'prepend' => '',
			'append' => '',
			'maxlength' => 20,
		),
		array(
			'key' => 'field_60ff058c8e5b9',
			'label' => 'Content',
			'name' => 'banner_content',
			'type' => 'textarea',
			'instructions' => 'Max characters: 250',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 250,
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_60ff05e98e5ba',
			'label' => 'Link',
			'name' => 'banner_links',
			'type' => 'repeater',
			'instructions' => 'Max links: 2',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 2,
			'layout' => 'table',
			'button_label' => 'Add Link',
			'sub_fields' => array(
				array(
					'key' => 'field_612fb6b81eabe',
					'label' => 'Banner Link',
					'name' => 'banner_link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
    );
}