<?php

function acf_lower_banner()
{
    return array(
		array(
			'key' => 'field_61847ccace3db',
			'label' => 'Lower Banner',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_61847cdbce3dc',
			'label' => 'Lower Banner Image',
			'name' => 'lower_banner_image',
			'type' => 'image',
			'instructions' => 'Recommended size 500x400.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_61847ce9ce3dd',
			'label' => 'Lower Banner Title',
			'name' => 'lower_banner_title',
			'type' => 'text',
			'instructions' => 'Max Characters: 50',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 50,
		),
		array(
			'key' => 'field_61847cf3ce3de',
			'label' => 'Lower Banner Description',
			'name' => 'lower_banner_description',
			'type' => 'textarea',
			'instructions' => 'Max Characters: 200',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 200,
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_61847d07ce3df',
			'label' => 'Lower Banner Button',
			'name' => 'lower_banner_button',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
    );
}