<?php

function acf_hero()
{
    return array(
		array(
			'key' => 'field_5f5f70a43c445',
			'label' => 'Hero',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e7cae3375f91',
			'label' => 'Hero Overlay',
			'name' => 'hero_overlay',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'No Overlay',
				'0.125' => 'Extra Light Overlay',
				'0.25' => 'Light Overlay',
				'0.5' => 'Medium Overlay',
				'0.75' => 'Heavy Overlay',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6124f4ba89662',
			'label' => 'Parallax Scrolling',
			'name' => 'hero_parallax',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5e7cae336b5e8',
			'label' => 'Hero Type',
			'name' => 'is_video',
			'type' => 'true_false',
			'instructions' => 'This section is shown at the top of the Homepage.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Video',
			'ui_off_text' => 'Image',
		),
		array(
			'key' => 'field_5e7cae3367ff3',
			'label' => 'Slider: Image',
			'name' => 'slider_image',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e7cae336b5e8',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '75',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 1,
			'max' => 6,
			'layout' => 'block',
			'button_label' => 'Add Slide',
			'sub_fields' => array(
				array(
					'key' => 'field_60ff12b219e39',
					'label' => 'Image',
					'name' => 'hero_slider_image',
					'type' => 'image',
					'instructions' => 'Recommended size 1650x900.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_60ff12c219e3a',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => 'Max characters: 70',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 70,
				),
				array(
					'key' => 'field_60ff12cd19e3z',
					'label' => 'Text',
					'name' => 'text',
					'type' => 'text',
					'instructions' => 'Max characters: 30',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 30,
				),
				// array(
				// 	'key' => 'field_60ff12cd19e3b',
				// 	'label' => 'Links',
				// 	'name' => 'links',
				// 	'type' => 'repeater',
				// 	'instructions' => '',
				// 	'required' => 0,
				// 	'conditional_logic' => 0,
				// 	'wrapper' => array(
				// 		'width' => '',
				// 		'class' => '',
				// 		'id' => '',
				// 	),
				// 	'collapsed' => '',
				// 	'min' => 0,
				// 	'max' => 2,
				// 	'layout' => 'table',
				// 	'button_label' => '',
				// 	'sub_fields' => array(
				// 		array(
				// 			'key' => 'field_60ff12e019e3c',
				// 			'label' => 'Link',
				// 			'name' => 'link',
				// 			'type' => 'link',
				// 			'instructions' => '',
				// 			'required' => 0,
				// 			'conditional_logic' => 0,
				// 			'wrapper' => array(
				// 				'width' => '',
				// 				'class' => '',
				// 				'id' => '',
				// 			),
				// 			'return_format' => 'array',
				// 		),
				// 		array(
				// 			'key' => 'field_61098cd8e212a',
				// 			'label' => 'Background Color',
				// 			'name' => 'hero_button_background_color',
				// 			'type' => 'select',
				// 			'instructions' => '',
				// 			'required' => 0,
				// 			'conditional_logic' => 0,
				// 			'wrapper' => array(
				// 				'width' => '',
				// 				'class' => '',
				// 				'id' => '',
				// 			),
				// 			'choices' => array(
				// 				'primary' => 'Primary',
				// 				'transparent' => 'Transparent',
				// 			),
				// 			'default_value' => false,
				// 			'allow_null' => 0,
				// 			'multiple' => 0,
				// 			'ui' => 0,
				// 			'return_format' => 'value',
				// 			'ajax' => 0,
				// 			'placeholder' => '',
				// 		),
				// 	),
				// ),
			),
		),
		array(
			'key' => 'field_5f5a50cf7309c',
			'label' => 'Slider: Video',
			'name' => 'slider_video',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e7cae336b5e8',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '75',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_612ecc6e792c0',
					'label' => 'Poster Image',
					'name' => 'poster_image',
					'type' => 'image',
					'instructions' => '*optional, shows while video is loading',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_612ed07f792c1',
					'label' => 'webm',
					'name' => 'webm',
					'type' => 'file',
					'instructions' => 'Video in webm format',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'webm',
				),
				array(
					'key' => 'field_612ed0a0792c2',
					'label' => 'mp4',
					'name' => 'mp4',
					'type' => 'file',
					'instructions' => 'Video in mp4 format',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '34',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				),
			),
		),
    );
}